# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='GuestTotal',
        ),
    ]
