# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20171025_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestTotal',
            new_name='GuestList',
        ),
    ]
