# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20171025_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='guestlist',
            name='second_name',
        ),
        migrations.AddField(
            model_name='guestlist',
            name='spouse',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
    ]
